### ISSUE TITLE
Refactored your project

### ISSUE THREAD

**Issue by Rehabescapi** [GUITARPLRC/React-Movie#10]
Hi I found your portfolio a few months ago and thought your movie app would be an interesting project to reproduce. 
[Live](https://reactreduxmovie.firebaseapp.com) 
[Repo](https://github.com/Rehabescapi/MovieDetails/tree/Appv1)

I implemented it with React/Redux with an initial approach to keeping the front end looking as similar as possible. Just wanted to give you a heads up before and a chance to ask for any changes before I add it to my portfolio. 

app/config/constants has a template file to add your api keys.

Thanks,
Jason

**Comment by GUITARPLRC** [comment]
Hi there!
I really don't mind what you did, but theres a few ways I would have gone about using someone else's work.
First, I would have starred the repo to show recognition that you like it, most people put a lot of work into what they do, so it's nice when someone notices.
Second, I would fork the repo, and then add changes.
All my repos are open source so, you can do what you want, and I do appreciate letting me know! Other than that, have fun!
